# This is a basic workflow to help you get started with Actions

name: Autify for Mobile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    env:
      #  specify the Xcode version Explicitly
      DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

    steps:
      - uses: actions/checkout@v2
      
      # [Optional step]
      - name: CI environment information
        run: |
           printf "\n→ sw_vers"
           sw_vers
           
           printf "\n→ ls -n /Applications/ | grep Xcode"
           ls -n /Applications/ | grep Xcode
           
           printf "\n→ xcodebuild -version"
           xcodebuild -version
           
           printf "\n→ xcpretty --version"
           xcpretty --version
           
           printf "\n→jq --version"
           jq --version

      # [Required step]
      # Builds a new build file
      # 
      # xcodebuild
      #   [-project <projectname>] or [-workspace <workspacename>] \
      #   -scheme <schemeName> \
      #   -destination <destinationspecifier>
      #   -configuration <configurationname> \
      #   -showBuildSettings \
      #   COMPILER_INDEX_STORE_ENABLE=NO \
      #   build | xcpretty
      - name: Build a new build file for iOS Simulator
        run: |
          readonly SIMULATOR_ID=$(xcrun simctl list devices --json | jq '.devices.'\"com.apple.CoreSimulator.SimRuntime.iOS-14-4\"'[] | select(.name=="iPhone 12").udid')
          
          echo $SIMULATOR_ID
        
